Session/9 スレッドブロック
ribilynn/yumemi-ios-training pull request #10
Opened 2022-04-20 01:32 UTC by ribilynn

## 課題
- 呼び出しAPIを`Sync ver`に変更する
- APIの処理が戻るまでUIActivityIndicatorを表示する

<img src="https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Images/ThreadBlock.gif?raw=true" width="350">

2022-04-20 02:01 UTC, novr reviewed
[NITS] ダークモードにすると時間表示が見えなくなってしまいます

2022-04-20 02:01 UTC, novr commented on yumemi-ios-training/View/WeatherViewController.swift
> +        DispatchQueue.global().async { [weatherModel, weak self] in
[IMO] 読み込みボタン連打すると...
loadingの状態はどの責務が管理すべきでしょうか？

2022-04-20 02:17 UTC, yumemi-rnose requested changes
気になったのでコメントしました。

2022-04-20 02:17 UTC, yumemi-rnose commented on yumemi-ios-training/View/WeatherViewController.swift
> +        DispatchQueue.global().async { [weatherModel, weak self] in
[IMO]
ViewがModelのスレッドの制御まで行っているのでModel側でやらせたほうがいいと思います。

2022-04-20 02:17 UTC, yumemi-rnose commented on yumemi-ios-training/View/WeatherViewController.swift
> +                DispatchQueue.main.async {
[IMO]
この部分と下記の部分も冗長な書き方なので `Result<Success, Error>`型でとるcallbackに形式にするといいかもですがどうでしょう？

2022-04-20 02:24 UTC, ribilynn commented on yumemi-ios-training/View/WeatherViewController.swift
> +        DispatchQueue.global().async { [weatherModel, weak self] in
WeatherModel に持つべきだと思います。だとすると Combine を使うことになりますが。

2022-04-20 02:39 UTC, ribilynn commented on yumemi-ios-training/View/WeatherViewController.swift
> +                DispatchQueue.main.async {
Callback は [Session 11](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Closure.md) の課題ですが… 今は 返す結果を `Result` にすることだけでもいいですけど。
```swift
DispatchQueue.global().async { [weatherModel, weak self] in
    let weatherResult = weatherModel.fetchWeather(area: "Tokyo", date: Date())
    DispatchQueue.main.async {
        switch weatherResult {
        case .success(let weather):
            self?.showWeather(weather)
        case .failure(let error):
            self?.presentError(error, showErrorDetail: false)
        }
        self?.activityView.stopAnimating()
    }
}
```

2022-04-20 02:50 UTC, ribilynn commented
この課題の後にある３つの課題が [Delegate](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Delegate.md), [Closure](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Closure.md), [Concurrency](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Concurrency.md) のなで、この３つのパターンを使わず、Loading 状態の管理も Thread の制御が全部 VC 内に行うのがこの課題の目的だと認識していますが合ってますか？

2022-04-20 03:42 UTC, novr commented
> 全部 VC 内に行うのがこの課題の目的だと認識していますが合ってますか？

特にVC内に限定する目的はないです、適宜必要に応じてアーキテクチャなどは使ってください:bow:

2022-04-20 08:06 UTC, ribilynn commented
一旦閉じます

2022-04-20 08:50 UTC, ribilynn commented
MVVM じゃないので、やはり loading 状態は VC が管理すべきだと思います。

変更点多いですが、再びレビューをお願いします。

2022-04-20 12:20 UTC, novr reviewed
MVCかMVVMかはあまり関係はなく、PDSで考えると
APIとのやりとり中かどうかはドメイン(Model)の関心ごとですね
Viewはmodelの状態を表示するのが責務です

2022-04-20 12:20 UTC, novr commented on yumemi-ios-training/Network/WeatherRequest+Client.swift
> +import Combine
[NITS] 不要では？

2022-04-22 00:44 UTC, yumemi-rnose approved these changes

2022-04-22 00:49 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/112428)

2022-04-22 00:51 UTC, merged

2022-04-22 00:51 UTC, ribilynn commented
レビューありがとうございます。