Session/2
ribilynn/yumemi-ios-training pull request #2
Opened 2022-04-07 09:09 UTC by ribilynn

"Reload" ボタンを押すと天気のアイコンが出てくれるようになりました。

2022-04-07 09:17 UTC, novr requested changes
この Session でやる課題内容がわからないです
概要に Session に対応する課題へのリンクだったり、求められている仕様を書いておきましょう

例

- やったこと
- 課題へのリンク
- API 仕様やデザイン定義へのリンク
- 実行画面（差分などあれば）

2022-04-08 01:26 UTC, ribilynn commented
PRも研修の一部であることを忘れました💦失礼しました

2022-04-08 04:37 UTC, yumemi-rnose reviewed
気になる点コメントしましたのでご確認ください。

2022-04-08 04:37 UTC, yumemi-rnose commented on yumemi-ios-training/Assets.xcassets/weather-icon/icon-cloudy.imageset/Contents.json
> +      "filename" : "icon-cloudy.pdf",
[IMO]
pdf はベクター画像なので、特にラスター画像として扱いたい理由がなければそのままベクター画像として扱うのが一般的です。

- Preserve Vector Data を ON に
- Scales を Single Scale に

することでそのように扱えると思います。
3 枚とも修正お願いします

参考: https://qiita.com/okamu_/items/085cfc5999db801020ff

2022-04-08 04:37 UTC, yumemi-rnose commented on yumemi-ios-training/WeatherUtility.swift
> +enum WeatherUtility {
[IMO]
Utilityはたとえコメントが記載されていても役割が不明瞭なので代わりに以下のようにするのはどうでしょう？

- ファイル名変更
`WeatherUtility.swift` → `WeatherViewController+Presentation.swift`
- enum ではなく WeatherViewControllerのextensionに
`enum WeatherUtility {` → `extension WeatherViewController {`

2022-04-08 04:37 UTC, yumemi-rnose commented on yumemi-ios-training/WeatherUtility.swift
> +    static func icon(for weather: String) -> UIImage? {
[IMO]
メソッドなのかコンピューテッドプロパティなのかわかりにくいのでメソッドであれば動詞から始まる名前にしたほうがわかりやすいと思います。

2022-04-08 05:16 UTC, ribilynn commented on yumemi-ios-training/WeatherUtility.swift
> +enum WeatherUtility {
今後他の ViewController が同じく天気アイコンを取得したい場合もありかもしれないと思って、VCから切り離したんですけど、その場合はどうすればいいですか？

2022-04-08 06:25 UTC, novr commented on yumemi-ios-training/WeatherUtility.swift
> +enum WeatherUtility {
[IMO] 名前空間としてのenumですね
やはりUtilityが不用なのでenum Weatherで良いかと思います

2022-04-08 06:25 UTC, novr commented on yumemi-ios-training/WeatherUtility.swift
> +    static func icon(for weather: String) -> UIImage? {
[IMO] 用法的にはicon(from:)のが直感的かと思います

2022-04-08 06:40 UTC, ribilynn commented on yumemi-ios-training/WeatherUtility.swift
> +    static func icon(for weather: String) -> UIImage? {
似たようなものもあるんで [icon(for:)](https://developer.apple.com/documentation/appkit/nsworkspace/3553230-icon) これでいきます。

2022-04-08 07:14 UTC, yumemi-rnose commented on yumemi-ios-training/WeatherUtility.swift
> +enum WeatherUtility {
↑ひとまずいいと思います。

2022-04-10 23:49 UTC, yumemi-rnose approved these changes
![LGTM](https://image.lgtmoon.dev/162680)

2022-04-11 00:48 UTC, merged