Change API to json version
ribilynn/yumemi-ios-training pull request #4
Opened 2022-04-11 06:29 UTC by ribilynn

## [Session4](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Json.md) 課題
- 呼び出しAPIを`Json ver`に変更する
- 天気予報を画面に表示する
  - 天気
  - 最低気温
  - 最高気温

## 実装効果

<img src="https://user-images.githubusercontent.com/11924267/162676616-b533d7b1-e945-41cf-a29a-4e1c24c9bfda.jpg" width="300">

## 解説

API から返された JSON 結果を解析する部分は VC から切り離すべきだったが、今後そういった課題があるので、ここで一旦 VC 内に留めます。

2022-04-11 07:13 UTC, yumemi-rnose requested changes
コメントしましたのでご確認ください。

2022-04-11 07:13 UTC, yumemi-rnose commented on yumemi-ios-training/WeatherViewController.swift
> +    let minTempLabel = UILabel()
`Temp` はいろんな略称を指すので使わない方がいいと思います。

2022-04-11 07:13 UTC, yumemi-rnose commented on yumemi-ios-training/WeatherViewController.swift
> +            let requestString = """
[IMO]
一つのメソッド内に色々やりすぎかと思いますので部分的にメソッドを切って呼び出す方がいいかと思います。

2022-04-11 07:35 UTC, ribilynn commented on yumemi-ios-training/WeatherViewController.swift
> +    let minTempLabel = UILabel()
同じくそう思っています！（[YumemiPackage 内部](https://github.com/yumemi-inc/ios-training/blob/44e166a75788370f85de090f47930645ee0ad069/Sources/YumemiWeather/YumemiWeather.swift#L8)ではこういう略称使っていますが）

2022-04-12 08:44 UTC, yumemi-rnose commented on yumemi-ios-training/WeatherViewController.swift
> +            let requestString = """
[ask]
あれ？なんで `enum Weather` 側にごそっと移したんでしょう？RequestParameter作成部分とリクエストデータ解析部分をVC内にするんじゃないんですかね？

2022-04-12 09:07 UTC, ribilynn commented on yumemi-ios-training/WeatherViewController.swift
> +            let requestString = """
野瀬さんがおしゃった「メソッドを切って呼び出す」というのを「UIに関係ない部分をVCから切り離す」に勘違いしました。全部VCに戻すなら、こうで合ってますかね：
```swift
    private func makeWeatherRequest(area: String, date: Date = Date()) -> String {
        """
        {
            "area": "\(area)",
            "date": "\(Weather.dateFormatter.string(from: date))"
        }
        """
    }
    
    private func parseWeatherResponse(_ json: String) throws -> (
        minTemperature: Int,
        maxTemperature: Int,
        weatherName: String
    )? {
        if let data = json.data(using: .utf8),
           let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
           let minTemperature = json["min_temp"] as? Int,
           let maxTemperature = json["max_temp"] as? Int,
           let weatherName = json["weather"] as? String {
            return (minTemperature, maxTemperature, weatherName)
        } else {
            return nil
        }
    }
    
    private func receiveWeather(
        minTemperature: Int,
        maxTemperature: Int,
        weatherName: String
    ) {
        minTemperatureLabel.text = String(minTemperature)
        maxTemperatureLabel.text = String(maxTemperature)
        imageView.image = Weather.icon(for: weatherName)
    }
    
    private func reloadWeather() {
        do {
            let weatherRequest = makeWeatherRequest(area: "Tokyo")
            let weatherResponse = try YumemiWeather.fetchWeather(weatherRequest)
            if let parsedResponse = try parseWeatherResponse(weatherResponse) {
                receiveWeather(
                    minTemperature: parsedResponse.minTemperature,
                    maxTemperature: parsedResponse.maxTemperature,
                    weatherName: parsedResponse.weatherName
                )
            }
        } catch {
            presentError(error)
        }
    }
```

2022-04-13 03:39 UTC, novr commented on yumemi-ios-training/WeatherViewController.swift
> +            let requestString = """
ModelとしてVCからロジックを切り出す目的でしたら、`Weather`に移動で良いかと思います

2022-04-13 07:21 UTC, ribilynn commented on yumemi-ios-training/WeatherViewController.swift
> +            let requestString = """
リクエスト作成、送り、結果の解析は別々の方法の中にやるべきということをわかっていますが、今はコード量がそんなに多くないので一つの方法にまとまりたいと思います。マージしまーす

2022-04-13 07:21 UTC, merged