Session/5 Codable
ribilynn/yumemi-ios-training pull request #5
Opened 2022-04-13 08:05 UTC by ribilynn

[Session 5 の課題](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Codable.md)です
## 課題
APIのリクエスト&レスポンスを Codable で扱う
- Codable の仕組みを利用して、`YumemiWeather`のAPIのパラメータを作成する
- Codable の仕組みを利用して、`YumemiWeather`のAPIの結果を扱う

## やったこと
- `WeatherRequest`を定義
- `Weather`を naming space からモデルの意味に変わる
- `Weather`のリクエスト関連の部分を`WeatherClient`に移って Codable を使って書き直す
- `WeatherViewController`, `Weather`を展示する部分を`reloadWeather`から切り離す

## 感想
この部分のコードを一体どこに属すればいいの？って書けば書くほど分からなくなってきました。
これで最適とは思わないので、アドバイスがあればぜひお願いします。

2022-04-13 08:37 UTC, novr commented
> この部分のコードを一体どこに属すればいいの？って書けば書くほど分からなくなってきました。
> これで最適とは思わないので、アドバイスがあればぜひお願いします。

アーキテクチャを考えてみるといいかと思います
まずはViewとそれ以外を分けるレイヤードアーキテクチャとして
ディレクトリから分けてみるといいと思います

2022-04-13 08:57 UTC, ribilynn commented
> Viewとそれ以外を分ける

これはわかりますが…知りたいのは、例えば Weather の dateFormater, encoder, decoder は、Weather に属するべきか、WeatherClient に属するべきかというより具体的なケースです…

2022-04-13 09:13 UTC, novr commented
> 例えば Weather の dateFormater, encoder, decoder は、Weather に属するべきか、WeatherClient に属するべきかというより具体的なケースです

であれば、責務の話ですね
単一責任の原則というのがあります
https://www.ogis-ri.co.jp/otc/hiroba/others/OOcolumn/single-responsibility-principle.html

WeatherとWeatherClientの役割を考えてみましょう
Weatherは構造体です、Viewが表示するデータを持ち、Viewのためにデータを加工します
WeatherClientはクラスです、YumemiWeatherとのやりとりを行い、結果をWeather型に変換します

dateFormater, encoder, decoderは何の為に使われているかを意識すると
YumemiWeatherの結果をWeather型に変換するために使われているので、WeatherClientが持つべきとなります

ソフトウェア設計原則はSOLIDと言って他にもあるので調べてみるといいですね

2022-04-13 10:56 UTC, ribilynn commented
なるほど……SOLID はもう死ぬほど聞いていましたが、そして dateFormater, encoder, decoder は Client の職務範囲だとなんとなく感じてるんですが、もし他の人に なぜ と聞かれるとこのように SOLID に結びつけてはっきりした説明はできないな今の私は。
目から鱗が落ちました。さっきのアーキテクチャのも、細かい説明と資料ありがとうございます！！

2022-04-13 16:20 UTC, novr requested changes

2022-04-13 16:20 UTC, novr commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        decoder.dateDecodingStrategy = .formatted(dateFormatter)
`.iso8601`があります
https://developer.apple.com/documentation/foundation/jsondecoder/datedecodingstrategy/iso8601

2022-04-13 16:20 UTC, novr commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        encoder.dateEncodingStrategy = .formatted(dateFormatter)
Weather.dateは画面表示に使っていないですが、iPhoneの暦法を西暦（グレゴリオ暦）以外に変更してWeather.dateの中身を見てみましょう
![image](https://user-images.githubusercontent.com/47618299/163199150-adbbcbaa-be94-4f76-9a6c-745670d8c6c6.png)

2022-04-13 16:20 UTC, novr commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        let requestData = try WeatherClient.encoder.encode(request)
新たにEncodingErrorが発生する可能性があります、呼び出し側は想定されていますか？
https://developer.apple.com/documentation/swift/encodingerror

2022-04-15 00:06 UTC, ribilynn commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        decoder.dateDecodingStrategy = .formatted(dateFormatter)
`.iso8601` も考えたが念の為[ソースコード](https://github.com/yumemi-inc/ios-training/blob/44e166a75788370f85de090f47930645ee0ad069/Sources/YumemiWeather/YumemiWeather.swift#L32)と一致するようにしました

と思ってたが調べたら同じことでした。

2022-04-15 00:33 UTC, ribilynn commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        let requestData = try WeatherClient.encoder.encode(request)
いま En(De)codingError が発生するとそのエラーの英語説明がそのまま出てしまうんですが、「想定」というのはそれに対して特別な処理（＝別の説明をユーザーに見せる）をするんですか…？

<img src="https://user-images.githubusercontent.com/11924267/163497123-31a107d5-01fa-45b9-be1f-78235bb12f7f.png" width="300">

2022-04-15 01:02 UTC, ribilynn commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        encoder.dateEncodingStrategy = .formatted(dateFormatter)
そうですね。日本に変われば年が令和年になりますね。API側が指定してないので、必要でしたらこれをつければいいと思います。
```swift
dateFormatter.calendar = Calendar(identifier: Calendar.Identifier.gregorian)
```
ついでに日時も UI に表示してみました。
<img src="https://user-images.githubusercontent.com/11924267/163501542-f8b1f1b1-5eba-4a5f-88da-751f3f005b6c.png" width="300">

2022-04-15 02:17 UTC, novr commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        let requestData = try WeatherClient.encoder.encode(request)
encode/decodeのtryは追加されたコードで、呼び出し側への副作用があります
副作用：EncodingError/DecodingErrorが発生する可能性がある

EncodingError/DecodingErrorはLogic failureなのでユーザ側では対処不可ですね
なのでユーザ側へはエラーが起こったことのみ通知の形が望ましいです
https://qiita.com/koher/items/a7a12e7e18d2bb7d8c77

2022-04-15 02:27 UTC, ribilynn commented on yumemi-ios-training/WeatherRequest+Client.swift
> +        let requestData = try WeatherClient.encoder.encode(request)
元にあった `YumemiWeatherError.invalidParameterError` と `.unknownError` も Logic failure だから、つまり今起こり得るエラーがすべて Logic failure で、エラーの具体的原因をユーザーに見せずに、ただ「エラーが起こりました」という通知だけを出るのが望ましいですかね。

2022-04-18 01:59 UTC, yumemi-rnose commented on yumemi-ios-training/Weather.swift
> +    var icon: UIImage? {
Weather はModelだとするとここにVieｗが入りこんでしまってますので切り離したほうがよいかと思います。

WeatherIconなど別にした方がいいかと思いますがどうでしょう？

2022-04-18 02:04 UTC, ribilynn commented on yumemi-ios-training/Weather.swift
> +    var icon: UIImage? {
それ思っちゃいますけど、切り離し方がちょっと悩ましいです。Top-Level にするのはなにか違う気がして、だとすればこうするのはどうでしょう…？
```swift
enum Resource {
    func weatherIcon(_ weatherName: String) -> UIImage? {
        //...
```

2022-04-18 02:12 UTC, yumemi-rnose commented on yumemi-ios-training/Weather.swift
> +    var icon: UIImage? {
まだそっちの方がいいんじゃないですかね。
それかUIImageViewを継承したWeatherImageViewにしてそっちにプレゼンテーションロジックをもってきた方がいいかもですね。

2022-04-18 03:23 UTC, yumemi-rnose approved these changes
![LGTM](https://image.lgtmoon.dev/163615)

2022-04-18 05:23 UTC, merged